# coding=UTF-8
'''
Initial method designed in December 2012, School of Electrical Engineering, Univeristy of Belgrade
Python implementation added on 7 May 2015 at the University of Manchester, School of Computer Science
Updated on 11.16.2021 at Serbian AI Society
@author: Nikola Milosevic
'''
from typing import List

from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')

rules = {
    'ovnicxki': '',
    'ovnicxka': '',
    'ovnika': '',
    'ovniku': '',
    'ovnicxe': '',
    'kujemo': '',
    'ovacyu': '',
    'ivacyu': '',
    'isacyu': '',
    'dosmo': '',
    'ujemo': '',
    'ijemo': '',
    'ovski': '',
    'ajucxi': '',
    'icizma': '',
    'ovima': '',
    'ovnik': '',
    'ognu': '',
    'inju': '',
    'enju': '',
    'cxicyu': '',
    'sxtva': '',
    'ivao': '',
    'ivala': '',
    'ivalo': '',
    'skog': '',
    'ucxit': '',
    'ujesx': '',
    'ucyesx': '',
    'ocyesx': '',
    'osmo': '',
    'ovao': '',
    'ovala': '',
    'ovali': '',
    'ismo': '',
    'ujem': '',
    'esmo': '',
    'asmo': '',  # pravi gresku kod pevasmo
    'zxemo': '',
    'cyemo': '',
    'cyemo': '',
    'bemo': '',
    'ovan': '',
    'ivan': '',
    'isan': '',
    'uvsxi': '',
    'ivsxi': '',
    'evsxi': '',
    'avsxi': '',
    'sxucyi': '',
    'uste': '',
    'icxe': 'i',  # bilo ik
    'acxe': 'ak',
    'uzxe': 'ug',
    'azxe': 'ag',  # mozda treba az, pokazati, pokazxe
    'aci': 'ak',
    'oste': '',
    'aca': '',
    'enu': '',
    'enom': '',
    'enima': '',
    'eta': '',
    'etu': '',
    'etom': '',
    'adi': '',
    'alja': '',
    'nju': 'nj',
    'lju': '',
    'lja': '',
    'lji': '',
    'lje': '',
    'ljom': '',
    'ljama': '',
    'zi': 'g',
    'etima': '',
    'ac': '',
    'becyi': 'beg',
    'nem': '',
    'nesx': '',
    'ne': '',
    'nemo': '',
    'nimo': '',
 